spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_drum?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: adminthn
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 154.8.236.244
    port: 6379
    password: adminthn
    timeout: 5000
    database: 0  #连接超时时间（毫秒)
    lettuce:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

  mail:
    #
    host: smtp.qq.com
    username: 767174855@qq.com
    password: mpkjpgzmhjfubgah
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#        smtps:
#          auth: true
#            starttls:
#              enable: true
#              required: true

server:
  port: 8080

jwt:
  ttl: 86400000
  key: drumTokenJwt

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)