spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_drum?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sa-token:
    # token名称（同时也是cookie名称）
    token-name: satoken
    # token有效期，单位s 默认30天，-1为永不过期
    timeout: 2592000
    # 在多人登录同一账号时，是否共享会话（为true时共用一个，为false时新登录挤掉旧登录）
    is-share: true
    # 是否在cookie读取不到token时，继续从请求header里继续尝试读取
    is-read-head: true
    #  是否在header读取不到token时，继续从请求题参数里继续尝试读取
    is-read-body: true
    # 是否在初始化配置时打印版本字符画
    is-v: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    database: 0  #连接超时时间（毫秒)
    lettuce:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

  mail:
    # 163
    host: smtp.qq.com
    port:
    username: 767174855@qq.com
    password: mpkjpgzmhjfubgah
    protocol: smtp,smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

#eureka:
#  client:
#    fetch-registry:
#    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/

jwt:
  ttl: 86400000
  key: drumTokenJwt

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)